clc;
clear;
%A = [0.3 0.4 0.5];
A = input("Enter Membership Function values for first fuzzy set: ");
%B = [0.2 0.7 0.4];
B = input("Enter Membership Function values for second fuzzy set: ");
%C = [0.1 0.2 0.9];
C = input("Enter Membership Function values for third fuzzy set: ");
BUC = max(B,C);
LHS = max(A,BUC);
AUB = max(A,B);
RHS = max(AUB, C);

disp("Set A");
disp(A);
disp("Set B");
disp(B);
disp("Set C");
disp(C);
disp("Required to prove A∪(B∪C) = (A∪B)∪C ");
disp("LHS = ");
disp(LHS);
disp("RHS = ");
disp(RHS);
disp("Therefore Associtive law holds");